// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google"; 
import Script from "next/script"; // 1. Import the Next.js Script component
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Poppins: display face — logo, hero headlines, section titles
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

// Inter: body/UI face — dashboards, tables, forms. Built for density and small sizes.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// 🚀 ADVANCED SEO & SOCIAL SHARING METADATA
export const metadata: Metadata = {
  title: "VAIDYA ERP | Ayurvedic Clinic & Hospital Management Software India",
  description: "Stop paying aggregator commissions. Manage your appointments, pharmacy POS, billing, and WhatsApp reminders from one secure dashboard. Start your 15-day free Premium trial.",
  keywords: [
    "Clinic Management Software",
    "Ayurveda ERP",
    "Ayurvedic Hospital Software",
    "Panchakarma Management Software",
    "Pharmacy POS software",
    "Hospital Management Software India",
    "Clinic Billing Software",
    "Patient Management System",
    "Appointment Scheduling Software for Clinics",
    "WhatsApp CRM for Clinics",
    "Ayurvedic Clinic Software India",
    "Multi-specialty Hospital ERP",
  ],
  authors: [{ name: "Rahul Chauhan" }],
  
  // Favicon and App Icons
  icons: {
    icon: "/favicon.ico", 
    shortcut: "/favicon.ico", 
    apple: "/apple-touch-icon.png", 
  },

  openGraph: {
    title: "VAIDYA ERP | Smart Clinic Management Software",
    description: "Run your entire clinic without the chaos. 0% commissions, 100% data ownership.",
    url: "https://vaidyaerp.in", 
    siteName: "VAIDYA ERP",
    images: [
      {
        url: "/og-image.jpg", 
        width: 1200,
        height: 630,
        alt: "VAIDYA ERP Dashboard Preview",
      },
    ],
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "VAIDYA ERP | Smart Clinic Management Software",
    description: "Run your entire clinic without the chaos. 0% commissions, 100% data ownership.",
    images: ["/og-image.jpg"],
  },
};

// Structured data (JSON-LD) — helps search engines understand what VAIDYA ERP is
// and can surface rich results (pricing, ratings) rather than a plain blue link.
const structuredData = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "VAIDYA ERP",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web",
  description: "Clinic and hospital management software for Ayurvedic and multi-specialty clinics in India — patients, appointments, pharmacy billing, and WhatsApp automation in one dashboard.",
  url: "https://vaidyaerp.in",
  offers: [
    {
      "@type": "Offer",
      name: "Basic Plan",
      price: "999",
      priceCurrency: "INR",
      priceValidUntil: "2027-12-31",
    },
    {
      "@type": "Offer",
      name: "Premium Plan",
      price: "2999",
      priceCurrency: "INR",
      priceValidUntil: "2027-12-31",
    },
  ],
  provider: {
    "@type": "Organization",
    name: "VAIDYA ERP",
    url: "https://vaidyaerp.in",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* SEO: structured data so search engines can understand VAIDYA ERP as a product */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />

        {/* 2. Add Google Analytics Scripts Here */}
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=G-7E6C8BZK9P`}
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-7E6C8BZK9P');
            `,
          }}
        />
      </head>
      <body className={`${poppins.variable} ${inter.variable} font-sans antialiased bg-[#F6F9F8] text-slate-800`}>
        <Header/>
        {children}
        <Toaster position="top-right" />
        <Footer/>
      </body>
    </html>
  );
}
